/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconF {
  IconF._();

  static const _kFontFam = 'iconfont';

  static const IconData close = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData falling = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData good = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData leftbutton = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData resonserate = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData good_fill = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData resonserate_fill = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData collection = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData collection_fill = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData account_fill = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData home_fill = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData account = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData comments = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80e, fontFamily: _kFontFam);
}
